### PR TITLE
fixed login to retreive clientid and respond with object

### LINKED ISSUE #14: Change password validation to not use hashing
The crypto library which has the hashing function we are using with react isnt available on pages without SSL, so we wont be able to use it for now. It is best we remove it now and try to secure the site later.

### PR DESCRIPTION
**Pull request by anthonymesa**
fixes #14

### CODE REVIEW

File: server.js [hunk 1]
```diff
@@ -191,7 +189,7 @@ function set_routes(server, db_connection) {
                 //  get the value by calling the .value attribute of the object. we can then set the true_password_hash
                 //  that we defined above to that value.
                 request.on('row', columns => {
-                    true_password = columns[0].value;
+                    user_id = columns[0].value;
                 });
```
Comment (JakeKeels) [inline server.js:193]: Must be a json object returned

File: server.js [hunk 2]
```diff
@@ -201,7 +199,7 @@ function set_routes(server, db_connection) {
                 //  if true is recieved, then the user would be logged in. if false is recieved, the user would be
                 //  told something along the lines of 'username or password incorrect'.
                 request.on('doneProc', function (rowCount, more, returnStatus, rows) {
-                    return resolve(true_password == password);
+                    return resolve(`{ client_id: '${user_id}'}`);
```
Comment (JakeKeels) [inline server.js:202]: Resolve as { status: x, value: { client_id: x } }

Comment (anthonymesa) [reply server.js:202]: awesome, I will fix this and push
